"""change column name

Revision ID: b50f37b61c20
Revises: 77f634349c75
Create Date: 2022-12-26 21:56:57.503675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50f37b61c20'
down_revision = '77f634349c75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('text', sa.String(), nullable=False))
    op.drop_column('notes', 'string')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('string', sa.VARCHAR(), nullable=False))
    op.drop_column('notes', 'text')
    # ### end Alembic commands ###
