"""fix

Revision ID: eb87e8993cf3
Revises: b50f37b61c20
Create Date: 2022-12-28 19:05:15.707744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb87e8993cf3'
down_revision = 'b50f37b61c20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notes', sa.Column('checked', sa.Boolean(), nullable=False))
    op.drop_column('notes', 'header')
    op.drop_column('notes', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('text', sa.VARCHAR(), nullable=False))
    op.add_column('notes', sa.Column('header', sa.VARCHAR(), nullable=False))
    op.drop_column('notes', 'checked')
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
